### PR TITLE
An alternate version of sudoku.py to consider

### PR DESCRIPTION
**Pull request by cclauss**
- Why create a Sudoku object when is all work is done in the `__init__()` method?
- Why have getImagePath() method that merely encapsulates os.path.abspath()?
- Why not create `res` on-the-fly (list comprehension or generator function)?
- create_net() takes a rel_path to enable benchmarks between different nets.
- Provide usage info to command line

### CODE REVIEW

**Comment by aulisius** [comment]
Wonderful change :D . Helps me get started with the server implementation

**Comment by prajwalkr** [comment]
The modified sudoku.py gives the following error:

``` python

Traceback (most recent call last):
  File "sudoku.py", line 41, in <module>
    snap_sudoku(image_path=sys.argv[1])
  File "sudoku.py", line 31, in snap_sudoku
    s = SudokuStr(''.join(cell for cell in get_cells(image_path)))
  File "sudoku.py", line 31, in <genexpr>
    s = SudokuStr(''.join(cell for cell in get_cells(image_path)))
  File "sudoku.py", line 24, in get_cells
    x = net.feedforward(np.reshape(cell, (784, 1)))
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 224, in reshape
    return _wrapit(a, 'reshape', newshape, order=order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 48, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: total size of new array must be unchanged
```

Do look into it @cclauss :smile:

**Comment by cclauss** [comment]
Did you retry this after the fix in https://github.com/prajwalkr/SnapSudoku/commit/a3b25dec58d644b259257060f12831a9677bf5cd ?

**Comment by prajwalkr** [comment]
No. Before fixing that issue.

**Comment by cclauss** [comment]
I think these two issues are related.  Can you please `sudoku_alt.py` again now that the https://github.com/prajwalkr/SnapSudoku/commit/a3b25dec58d644b259257060f12831a9677bf5cd fix is in?

If that does NOT work, can you please put this line BEFORE line 24 in `sudoku_alt.py` and let me know what gets printed?

``` python
        print('len(cell): {}'.format(len(cell)))
```

**Comment by prajwalkr** [comment]
Fixed it myself! :smile:

**Pull request merged**
