### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by tushar-rishav** [comment]
In future, stuff like this can be automatically fixed using [coala analyser](https://github.com/coala-analyzer/coala). @prajwalkr

**Comment by cclauss** [comment]
Agreed.  I did it automatically with PyCharm Community Edition...  There are other unused imports in other Python files in this project.  You can see if coala can find and eliminate them.

**Comment by tushar-rishav** [comment]
@cclauss  Yes coala can handle search recursively. Besides, It can be customised as per user's need. I shall implement it soonish. :+1:

**Comment by cclauss** [comment]
This should be fixed by issue https://github.com/prajwalkr/SnapSudoku/issues/14 fixes.

**Pull request closed without merging**
